Sprint 5/step 1
batolser/react-burger pull request #7
Opened 2023-04-24 00:40 UTC by batolser

2023-04-24 05:25 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;ы
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/pYlgpcYdZjn_Dw> - Нужно поправить вёрстку в соответствии с макетом.

  - Поправить скролл, он должен быть кастомным;
  - Поправить ширину элементов: <https://disk.yandex.com/i/J6t9U7iHYsnYdg>;
  - Добавить ещё 1 столбик `в процессе`: <https://disk.yandex.com/i/QPfZHaMkQHRAcg>;

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. Это можно проверить в девтулс, во вкладке `networks`.

- У вас никак не закрываются модальные окна, хотя по идее должны: <https://disk.yandex.com/i/rdqYSIB-msnp4Q>;

- Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` или `/feed/:id` в новой вкладке;

- Нужно исправить вёрстку страницы профиля: <https://disk.yandex.com/i/gcoIK5eeGKxn4w> <https://disk.yandex.com/i/PBLfMrHWiVDWkA>, чтобы она соответствовала макету: <https://disk.yandex.com/i/s6ZP4yXL161Ixw>, <https://disk.yandex.com/i/plIisDA4VJc4sQ>;

- В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

- <https://disk.yandex.com/i/WMQXj44yb3Sxrw> - По макету тут должен быть кастомный скролл;

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: - <https://disk.yandex.com/i/0Hzoqj30_t2iJw>;

### **Сделает код лучше:**

- Типы лучше писать рядом с компонентов, а не в отдельном файле;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-04-24 05:25 UTC, ArslanDev666 commented on src/components/stats/stats.tsx
> +                    orders?.some((order: IOrder) => order.status === 'done') && (
**Надо исправить:**

Здесь и далее, а почему бы сразу не сделать фильтрацию по статусу, и всё, тогда не нужно было бы делать двойную проверку.

```js
const {ordersDone, ordersPending} = {
 ordersDone: orders?.filter(...);
 ordersPending: orders?.filter(...);
}
```

Это ещё можно обернуть в `useMemo`)

2023-04-24 05:25 UTC, ArslanDev666 commented on src/pages/ingredient/ingredient.tsx
> +      );
**Надо исправить:**

Этот запрос избыточен, т.к. уже есть такой же в `app`, и получается, что вы два раза делаете запрос, что не очень хорошо))

2023-04-24 05:25 UTC, ArslanDev666 commented on src/pages/profile-feed/profile-feed.tsx
> +  console.log(getCookie("accessToken"))
**Надо исправить:**

Здесь и далее;

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-04-24 05:25 UTC, ArslanDev666 commented on src/pages/profile-feed/profile-feed.tsx
> +// }
**Можно лучше:**

такие большие куски кода лучше сразу удалять

2023-04-24 05:25 UTC, ArslanDev666 commented on src/pages/profile/profile-form.tsx
> +    const [password, setPassword] = useState("");
**Можно лучше:**

Поставьте себе `prettier`, чтобы всегда был один вид ковычек; Можно ещё `eslint` настроить на те или иные ковычки;

2023-04-24 05:25 UTC, ArslanDev666 commented on src/utils/api.tsx
> +export const api = 'https://norma.nomoreparties.space/api';
**Надо исправить:**

константы принято записывать в `UPPER_CASE`.

2023-04-24 05:25 UTC, ArslanDev666 commented on src/utils/api.tsx
> +export const getUsersDataRequest = async (accessToken: string) => {
**Надо исправить:**

Здесь и далее. Там, где вы передаёте токен в запрос.

Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-04-24 05:25 UTC, ArslanDev666 commented on src/utils/api.tsx
> +export const postOrderInfo = async (ingredientsIds: string[]) => {
**Надо исправить:**

Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

2023-04-24 05:25 UTC, ArslanDev666 commented on src/pages/profile/profile.tsx
> +        console.log("прошло")
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-04-24 05:25 UTC, ArslanDev666 commented on src/services/middleware/socket-middleware.tsx
> +        console.log('1')
**Надо исправить:**

Здесь и далее.

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-04-24 05:25 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.tsx
> +    const ingredient = useSelector((state:any) => state.modalReducer.ingredient);
**Надо исправить:**

вы типизировали `useSelector`, поэтому вам не нужно дополнительно указывать тут `any` (просто используйте свой `useSelector`).

2023-04-24 09:26 UTC, batolser commented on src/components/stats/stats.tsx
> +                    orders?.some((order: IOrder) => order.status === 'done') && (
по поводу верстки. есть же код для заказов в процессе: 
{
                    orders?.some((order: IOrder) => order.status === 'pending') && (
                      <div className={styles.in_process}>
                        <p className="text text_type_main-medium pb-6">
                          В работе:
                        </p>
                        <ul className={styles.list}>
                          {
                            orders?.map((order: IOrder, idx: number) => {
                              if (idx < 10 && order.status === 'pending') {
                                return (<li key={idx} className="text text_type_digits-default pb-2">
                                  {order.number}
                                </li>)
                              }
                              return null
                            })
                          }
                        </ul>
                      </div>
                    )
                  }

2023-04-25 12:30 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены;

### **Нужно будет исправить к следующему спринту:**

- Нужно исправить вёрстку страницы заказов в профиле:

  - Нужно расставить состояния в заказах: <https://disk.yandex.com/i/c58yzAw5a3EsfQ>;
  - Убрать скролл слева и отцентрировать весь контент, как это сдано в макет;
  - <https://disk.yandex.com/i/Kv6THk7u5BW3lg> - добавить расстояние между карточками;

- При закрытии WS соединения, у вас возникает ошибка (тригерится в редаксе), отследите причину ошибки и исправьте (написал в коде как можно исправить): <https://disk.yandex.com/i/n-lBk1ZA-EwS7w>;

- Старайтесь не писать пустые `console.error()`, это не очень правильно;

2023-04-25 12:30 UTC, ArslanDev666 commented on src/services/middleware/socket-middleware.tsx
> +          }
**Надо исправить:**

Тут нужно указывать ошибку `1005`, а не `1000`, ну или явно указать код)) 

https://github.com/vert-x3/issues/issues/297 - тут подробнее

2023-06-06 17:51 UTC, merged